Publishing workspace RPP - změny z DD3 (https://slovník.gov.cz/datový/pracovní-prostor/pojem/metadatový-kontext/instance1185261700)
datagov-cz/ssp pull request #627
Opened 2023-03-23 10:50 UTC by psiotwo

Changed vocabularies: 
 - https://slovník.gov.cz/datový/slovník-digitálního-česka (context https://slovník.gov.cz/datový/slovník-digitálního-česka/verze/b3f42d8a-c67a-48c9-8d7f-33c943275059)
 - https://slovník.gov.cz/legislativní/sbírka/111/2009 (context https://slovník.gov.cz/legislativní/sbírka/111/2009/verze/66097af9-ca4d-41f3-b834-8cb122953347)
 - https://slovník.gov.cz/agendový/104 (context https://slovník.gov.cz/agendový/104/verze/025ade3d-9bea-409c-8044-f979c9f5bc3f)

Changed attachments: 
 - https://slovník.gov.cz/příloha/instance-c2e48979-b34f-4baa-ad83-3e856fef1758 (context https://slovník.gov.cz/příloha/instance-c2e48979-b34f-4baa-ad83-3e856fef1758/verze/af5b8d8b-12fd-468f-b83a-24c43dd048a3)
 - https://slovník.gov.cz/příloha/instance-ed7b43d8-ace1-4dd1-a424-5a86e48bf2ac (context https://slovník.gov.cz/příloha/instance-ed7b43d8-ace1-4dd1-a424-5a86e48bf2ac/verze/c3dbef89-7e82-4c61-b847-6dff8e77ba65)
 - https://slovník.gov.cz/příloha/instance-ce370500-8876-461e-afca-860086497b84 (context https://slovník.gov.cz/příloha/instance-ce370500-8876-461e-afca-860086497b84/verze/d139b74c-4614-4724-b946-3d3cf3d0984b)
 - https://slovník.gov.cz/příloha/instance-ce370500-8876-461e-afca-860086497b84 (context https://slovník.gov.cz/příloha/instance-ce370500-8876-461e-afca-860086497b84/verze/38b6aebb-0fcc-4d53-99e7-0d01bf06dd4d)
 - https://slovník.gov.cz/příloha/instance-8b547f7f-6439-4b5f-b085-edaebbb6fb30 (context https://slovník.gov.cz/příloha/instance-8b547f7f-6439-4b5f-b085-edaebbb6fb30/verze/925c5128-259c-4089-a617-c82569015940)
 - https://slovník.gov.cz/příloha/instance-37e68ae0-e02f-4ae3-a977-c8398538e82d (context https://slovník.gov.cz/příloha/instance-37e68ae0-e02f-4ae3-a977-c8398538e82d/verze/adb84d8a-5bca-4193-8385-6e4daccfcfa1)
 - https://slovník.gov.cz/příloha/instance-cabe5ecb-6756-498c-8710-aaaf851debc9 (context https://slovník.gov.cz/příloha/instance-cabe5ecb-6756-498c-8710-aaaf851debc9/verze/d3546b16-492f-4658-b716-29ad7e9d7a56)
 - https://slovník.gov.cz/příloha/instance-a29c7d04-1a18-4388-b65f-a3dd8c87fc45 (context https://slovník.gov.cz/příloha/instance-a29c7d04-1a18-4388-b65f-a3dd8c87fc45/verze/a5f9a09b-8b7a-4e18-aca4-c28e93510213)
 - https://slovník.gov.cz/příloha/instance-e1d1d88f-3111-4bc3-856c-8d4a4b232ad0 (context https://slovník.gov.cz/příloha/instance-e1d1d88f-3111-4bc3-856c-8d4a4b232ad0/verze/a7f58799-b826-4847-aa80-306f17809e2d)
 - https://slovník.gov.cz/příloha/instance-73f55f60-053a-4a62-9e27-c9cce705a574 (context https://slovník.gov.cz/příloha/instance-73f55f60-053a-4a62-9e27-c9cce705a574/verze/795d4d17-634c-4877-860e-81112796c41f)
 - https://slovník.gov.cz/příloha/instance-a46a4ef0-1a6c-451b-b918-7d25e1e9daa8 (context https://slovník.gov.cz/příloha/instance-a46a4ef0-1a6c-451b-b918-7d25e1e9daa8/verze/0674843e-2450-48cb-939b-a9d963642cac)
 - https://slovník.gov.cz/příloha/instance-cabe5ecb-6756-498c-8710-aaaf851debc9 (context https://slovník.gov.cz/příloha/instance-cabe5ecb-6756-498c-8710-aaaf851debc9/verze/59f314df-098a-44a6-9e8c-1a20f60980d3)
 - https://slovník.gov.cz/příloha/instance-23577b2f-122c-44f1-a46e-b8bd04875269 (context https://slovník.gov.cz/příloha/instance-23577b2f-122c-44f1-a46e-b8bd04875269/verze/ee328463-018e-4ea8-80fa-9cb2536c2503)
 - https://slovník.gov.cz/příloha/instance-0efaa407-d644-4e84-a95a-17522bbde9ac (context https://slovník.gov.cz/příloha/instance-0efaa407-d644-4e84-a95a-17522bbde9ac/verze/405068e8-d722-481e-b694-43cde459c2f5)
 - https://slovník.gov.cz/příloha/instance-8b547f7f-6439-4b5f-b085-edaebbb6fb30 (context https://slovník.gov.cz/příloha/instance-8b547f7f-6439-4b5f-b085-edaebbb6fb30/verze/385da919-b2c0-40ac-ab2e-990eefb219c2)
 - https://slovník.gov.cz/příloha/instance-23577b2f-122c-44f1-a46e-b8bd04875269 (context https://slovník.gov.cz/příloha/instance-23577b2f-122c-44f1-a46e-b8bd04875269/verze/8c98b825-f368-40ea-a1ec-1be72c626ea3)
 - https://slovník.gov.cz/příloha/instance-ce370500-8876-461e-afca-860086497b84 (context https://slovník.gov.cz/příloha/instance-ce370500-8876-461e-afca-860086497b84/verze/90c2ef3e-1780-40a8-9801-6d667bba7d50)
 - https://slovník.gov.cz/příloha/instance-a46a4ef0-1a6c-451b-b918-7d25e1e9daa8 (context https://slovník.gov.cz/příloha/instance-a46a4ef0-1a6c-451b-b918-7d25e1e9daa8/verze/9ed795d8-6806-4fd5-9f56-e8f8af8d2270)
 - https://slovník.gov.cz/příloha/instance-c4b31d4b-4ad3-4f38-a67c-a898f6015e7e (context https://slovník.gov.cz/příloha/instance-c4b31d4b-4ad3-4f38-a67c-a898f6015e7e/verze/6281c69a-f21b-4ead-9999-42fbdae212b0)
 - https://slovník.gov.cz/příloha/instance-e1d1d88f-3111-4bc3-856c-8d4a4b232ad0 (context https://slovník.gov.cz/příloha/instance-e1d1d88f-3111-4bc3-856c-8d4a4b232ad0/verze/3f85c8e2-ea1c-42d2-823e-663f0ba0ceae)
 - https://slovník.gov.cz/příloha/instance-ed7b43d8-ace1-4dd1-a424-5a86e48bf2ac (context https://slovník.gov.cz/příloha/instance-ed7b43d8-ace1-4dd1-a424-5a86e48bf2ac/verze/913a6e65-e794-483e-a9b9-ec1b93be8281)
 - https://slovník.gov.cz/příloha/instance-23577b2f-122c-44f1-a46e-b8bd04875269 (context https://slovník.gov.cz/příloha/instance-23577b2f-122c-44f1-a46e-b8bd04875269/verze/6316e5da-c51e-4418-99c0-1895e3294cb6)
 - https://slovník.gov.cz/příloha/instance-c4b31d4b-4ad3-4f38-a67c-a898f6015e7e (context https://slovník.gov.cz/příloha/instance-c4b31d4b-4ad3-4f38-a67c-a898f6015e7e/verze/b963efeb-b9fd-4d0e-b759-bb857ef4f987)
 - https://slovník.gov.cz/příloha/instance-73f55f60-053a-4a62-9e27-c9cce705a574 (context https://slovník.gov.cz/příloha/instance-73f55f60-053a-4a62-9e27-c9cce705a574/verze/96f0fe1a-d98c-408a-8a1a-3f32aee69140)
 - https://slovník.gov.cz/příloha/instance-e1d1d88f-3111-4bc3-856c-8d4a4b232ad0 (context https://slovník.gov.cz/příloha/instance-e1d1d88f-3111-4bc3-856c-8d4a4b232ad0/verze/7d1f9fd9-5248-4223-8b62-bea34ba0bf0a)
 - https://slovník.gov.cz/příloha/instance-c2e48979-b34f-4baa-ad83-3e856fef1758 (context https://slovník.gov.cz/příloha/instance-c2e48979-b34f-4baa-ad83-3e856fef1758/verze/167c4398-02e6-485e-9731-0bb35affe568)
 - https://slovník.gov.cz/příloha/instance-ed7b43d8-ace1-4dd1-a424-5a86e48bf2ac (context https://slovník.gov.cz/příloha/instance-ed7b43d8-ace1-4dd1-a424-5a86e48bf2ac/verze/b36e272d-1990-4521-8e0d-418385b4e415)
 - https://slovník.gov.cz/příloha/instance-c4b31d4b-4ad3-4f38-a67c-a898f6015e7e (context https://slovník.gov.cz/příloha/instance-c4b31d4b-4ad3-4f38-a67c-a898f6015e7e/verze/263b8a25-99aa-4894-a1f7-8021fa183d14)
 - https://slovník.gov.cz/příloha/instance-c2e48979-b34f-4baa-ad83-3e856fef1758 (context https://slovník.gov.cz/příloha/instance-c2e48979-b34f-4baa-ad83-3e856fef1758/verze/0b925f33-aee6-41c9-b6c8-d2da7afec387)
 - https://slovník.gov.cz/příloha/instance-73f55f60-053a-4a62-9e27-c9cce705a574 (context https://slovník.gov.cz/příloha/instance-73f55f60-053a-4a62-9e27-c9cce705a574/verze/7bf952d0-9381-4a6c-aab5-db409eb1bc02)
 - https://slovník.gov.cz/příloha/instance-0efaa407-d644-4e84-a95a-17522bbde9ac (context https://slovník.gov.cz/příloha/instance-0efaa407-d644-4e84-a95a-17522bbde9ac/verze/6b0763bd-a6af-461f-869a-ad5d2078f869)
 - https://slovník.gov.cz/příloha/instance-a29c7d04-1a18-4388-b65f-a3dd8c87fc45 (context https://slovník.gov.cz/příloha/instance-a29c7d04-1a18-4388-b65f-a3dd8c87fc45/verze/c532be51-e73e-43ce-ab9d-bc2e2589d5c9)
 - https://slovník.gov.cz/příloha/instance-8b547f7f-6439-4b5f-b085-edaebbb6fb30 (context https://slovník.gov.cz/příloha/instance-8b547f7f-6439-4b5f-b085-edaebbb6fb30/verze/ace46a25-418c-473f-811a-02fae16a5efb)
 - https://slovník.gov.cz/příloha/instance-37e68ae0-e02f-4ae3-a977-c8398538e82d (context https://slovník.gov.cz/příloha/instance-37e68ae0-e02f-4ae3-a977-c8398538e82d/verze/e919a3bd-1897-45b5-b37f-b137f6b95697)
 - https://slovník.gov.cz/příloha/instance-0efaa407-d644-4e84-a95a-17522bbde9ac (context https://slovník.gov.cz/příloha/instance-0efaa407-d644-4e84-a95a-17522bbde9ac/verze/be91ed07-c15a-49f8-815e-a2709db9ef2e)
 - https://slovník.gov.cz/příloha/instance-a29c7d04-1a18-4388-b65f-a3dd8c87fc45 (context https://slovník.gov.cz/příloha/instance-a29c7d04-1a18-4388- [...]

2023-04-04 09:03 UTC, MichalMed requested changes

2023-04-04 09:03 UTC, MichalMed commented on content/vocabularies/v-sgov/v-sgov-glosář.ttl
1)  nejsem si jistý, jestli je dobré upravovat V-SGOV a
2) v TermItu nejsou pojmy validní a v yhazují chyby.

2023-04-04 09:03 UTC, MichalMed commented on content/vocabularies/v-sgov/v-sgov-glosář.ttl
celkově si mysloím, že by VSGoV neměl být vkládán do workspacu jako slovník k editaci

2023-04-05 08:00 UTC, trusinas commented on content/vocabularies/l-sgov-sbírka-106-1999/l-sgov-sbírka-106-1999-glosář.ttl
> +l-sgov-sbírka-106-1999-pojem:je-publikován-jako-datová-sada a skos:Concept;
Label a IRI opraveny. Definice doplním u všech chybějících později.

2023-04-05 08:03 UTC, trusinas commented on content/vocabularies/l-sgov-sbírka-111-2009/l-sgov-sbírka-111-2009-glosář.ttl
> +    l-sgov-sbírka-111-2009-pojem:je-publikován-jako-datová-sada, l-sgov-sbírka-111-2009-pojem:je-sdílen-v-ppdf,
Mezi pojmy 111/2009 jsem jej nenašel. Pokud tam je, může se smazat, jde opravdu o duplicitu.

2023-04-05 08:04 UTC, trusinas commented on content/vocabularies/v-sgov/v-sgov-glosář.ttl
VSGoV jsem z pracovního prostoru smazal a používám pojmy pouze pro čtení.

2023-04-07 18:11 UTC, MichalMed submitted a review, later dismissed

2023-04-07 21:00 UTC, merged